name: Deploy sls app

on: 
  push:
    branches:
      - main

jobs:     
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: install-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install serverless
      run: npm i -g serverless
    - name: .env File create
      run: |
        echo "DB_HOST=$DB_HOST" >> .env
        echo "DB_USER=$DB_USER" >> .env
        echo "DB_PASSWORD=$DB_PASSWORD" >> .env
        echo "DB_DATABASE=$DB_DATABASE" >> .env
        echo "SALT=$SALT" >> .env
        echo "JWT_SECRET_KEY=$JWT_SECRET_KEY" >> .env
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
        echo "S3_BUCKET=$S3_BUCKET" >> .env
        echo "GOOGLE_KEY=$GOOGLE_KEY" >> .env
        echo "NAVER_CLIENT_KEY=$NAVER_CLIENT_KEY" >> .env
        echo "NAVER_SECRET_KEY=$NAVER_SECRET_KEY" >> .env
      env:
        DB_HOST: ${{secrets.DB_HOST}}
        DB_USER: ${{secrets.DB_USER}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        DB_DATABASE: ${{secrets.DB_DATABASE}}
        SALT: ${{secrets.SALT}}
        JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        S3_BUCKET: ${{secrets.S3_BUCKET}}
        GOOGLE_KEY: ${{secrets.GOOGLE_KEY}}
        NAVER_CLIENT_KEY: ${{secrets.NAVER_CLIENT_KEY}}
        NAVER_SECRET_KEY: ${{secrets.NAVER_SECRET_KEY}}

    - run: serverless plugin install -n serverless-wsgi
    - name: severless deploy
      run: sls deploy --verbose --force
